name = "PyScriptWidgets"

packages = [
    "asyncio",
]

[files]
# Set the *base url* when deploying to: https://michielwestland.github.io/PyScriptWidgets
# "{BASE}" = "https://michielwestland.github.io/PyScriptWidgets"
"{BASE}" = "."
"{BASE}/widgets.py" = "./widgets.py"
"{BASE}/todo.py" = "./todo.py"

# See: https://pyscript.github.io/docs/2024.1.3/user-guide/configuration/#files
